[package]
name = "freepass-capi"
version = "0.0.0"
authors = [ "Val Packett <val@packett.cool>" ]
keywords = [ "Security", "Password", "MasterPassword" ]
description = "Freepass password/auth manager: C API"
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/valpackett/freepass"
repository = "https://github.com/valpackett/freepass"

[lib]
name = "freepass_capi"
crate-type = [ "dylib", "staticlib" ]

[dependencies]
freepass-core = { version = "0", path = "../core", default-features = false, features = [] }
secstr = { version = "0.3", features = ["serde", "libsodium-sys"] }
serde_cbor = "0.6"
sodiumoxide = "0"
rusterpassword = { version = "0", path = "../rusterpassword" }
rusterpassword-capi = { version = "0", path = "../rusterpassword/capi" }
colorhash256 = "0"
libc = "0.2"
